"""Textual pilots for live-think streaming from a delta log (M5 stage 3).

Stage 2 proved the FR-5.1 live-think *mechanism* (the current speaker's THINK
streams in a highlighted block and auto-collapses when TALK begins). Stage 3
proves it holds under the shapes a real producer creates:

* **(a)** a queue-fed live session where ``think_delta`` fragments accumulate
  visibly across *individual* pump steps (not one dump), the first ``talk_delta``
  collapses the live block, and the preserved thinking is **re-expandable** via
  the ``t`` key;
* **(b)** a *full mocked-debate delta log* — generated by the extended synthetic
  generator (:func:`tests.support.synthetic_events.build_delta_events`) whose
  fragments concatenate to the ``*_completed`` full_text — replays to the
  **identical final render state** as its completed-only twin (delta/completed
  consistency), both as a pure fold and through the real app;
* **(c)** the ``turn_interrupted`` badge renders its provenance (a ``system``
  interrupt is *not* mislabelled as the ``esc`` affordance), and ``esc`` in live
  mode always emits an :class:`~tinyic.tui.steering.InterruptRequest` through the
  :class:`~tinyic.tui.steering.ControlSink` — even with no active turn;
* **(d)** a JSONL **follower** feeding the UI: events appended to the file
  mid-test appear in the transcript, and a truncated (newline-less) tail is
  tolerated — never crashing, never fabricating a turn — then cleanly reassembled.

Determinism: every fold is driven by hand — the queue-fed pilots call
``_pump`` / ``replay_all_now`` explicitly, and the follower pilot pumps in a
bounded loop that waits on a *state* predicate (never a wall-clock deadline, the
same discipline as the follower unit tests' blocking ``queue.get(timeout=...)``).
No test asserts on elapsed time.
"""

from __future__ import annotations

import json
import queue
from collections import defaultdict

from tinyic.tui.app import TownHallApp
from tinyic.tui.events import parse_event, read_events
from tinyic.tui.live import attach_event_log_follower
from tinyic.tui.state import (
    ArtifactState,
    PhaseState,
    SteeringState,
    TownHallState,
    TurnState,
)
from tinyic.tui.steering import RecordingControlSink
from tinyic.tui.widgets import PersonaCard, StatusHeader, TurnCard

from tests.support import synthetic_events as G

TOTAL_TURNS = 22  # opening 6 + cross_exam 4 + rebuttal 6 + verdict 6


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

def _ev(type_: str, **payload):
    """One parsed :class:`Event` from a type + payload (no envelope needed)."""
    return parse_event({"type": type_, "payload": payload})


def _card(app: TownHallApp, turn_id: str) -> TurnCard:
    widget = app._item_widgets[f"turn-{turn_id}"]
    assert isinstance(widget, TurnCard)
    return widget


def _turn_count(app: TownHallApp) -> int:
    return sum(1 for i in app.state.transcript if isinstance(i, TurnState))


def _turn_speech(app: TownHallApp, turn_id: str) -> str | None:
    """The folded speech of ``turn_id``, or ``None`` if that turn isn't folded yet.

    Gating a live drain on this (rather than mere card existence) waits for the
    *content* under assertion — a turn's card mounts on ``turn_started``, but its
    speech only lands on the later ``talk_delta`` / ``talk_completed``, so gating
    on the card alone would race the rest of the turn.
    """
    for item in app.state.transcript:
        if isinstance(item, TurnState) and item.turn_id == turn_id:
            return item.speech
    return None


async def _step(app: TownHallApp, pilot) -> None:
    """Fold exactly one pump batch and let the resulting mount/sync settle."""
    app._pump()
    await pilot.pause()


async def _drain_until(app: TownHallApp, pilot, predicate, *, tries: int = 300) -> bool:
    """Pump the app (polling its live source) until ``predicate`` holds.

    The follower runs on a background thread appending to the app's queue; each
    iteration drains whatever it has produced onto the pump, folds it, then yields
    the event loop so the follower thread can make more progress. Returns once the
    predicate holds. ``tries`` is only a hang guard — the loop asserts a *state*
    condition, never a timing deadline (mirroring the follower unit tests'
    blocking ``queue.get(timeout=...)``).
    """
    for _ in range(tries):
        app.replay_all_now()
        await pilot.pause()
        if predicate():
            return True
    return predicate()


def _line(env: dict) -> str:
    """One newline-terminated JSONL record, matching the engine's writer."""
    return json.dumps(env, separators=(",", ":")) + "\n"


def _append(path, text: str) -> None:
    with open(path, "a", encoding="utf-8") as handle:
        handle.write(text)


def _env(seq: int, etype: str, **payload) -> dict:
    return {"v": 1, "seq": seq, "ts": "", "debate_id": "d", "type": etype, "payload": payload}


# --------------------------------------------------------------------------- #
# (a) Live: think_deltas accumulate across pump steps; talk collapses; re-expand.
# --------------------------------------------------------------------------- #

async def test_a_live_think_accumulates_across_pump_steps_and_reexpands():
    q: queue.Queue = queue.Queue()
    # batch_size=1: each pump folds exactly one event, so the running THINK
    # accumulation is observable *between* fragments — proof the deltas are paced
    # through the block, never dumped at once (FR-5.5 riding the FR-5.1 block).
    app = TownHallApp.live(q, auto_replay=False, batch_size=1)
    async with app.run_test() as pilot:
        await pilot.pause()
        for ev in (
            _ev("debate_started", ticker="AAPL",
                personas=[{"name": "Warren Buffett"}]),
            _ev("phase_started", phase="opening", index=0),
            _ev("turn_started", turn_id="t1", persona="Warren Buffett",
                phase="opening", role="statement"),
            _ev("think_delta", turn_id="t1", text="weighing "),
            _ev("think_delta", turn_id="t1", text="the durable "),
            _ev("think_delta", turn_id="t1", text="moat"),
        ):
            q.put(ev)

        # Fold the three lifecycle events (one per tick); the turn card mounts.
        for _ in range(3):
            await _step(app, pilot)
        card = _card(app, "t1")
        assert card.turn.thinking == ""            # no THINK folded yet
        assert card.turn.thinking_live is False     # streaming not begun
        assert card._think_live.display is False

        # Each subsequent tick folds one think_delta; the block accumulates.
        await _step(app, pilot)
        assert card.turn.thinking == "weighing "
        assert card.turn.thinking_live is True       # highlighted live block up
        assert card._think_live.display is True
        assert card._think.display is False           # standard row hidden
        assert "weighing" in str(card._think_live.render())

        await _step(app, pilot)
        assert card.turn.thinking == "weighing the durable "
        assert card.turn.thinking_live is True

        await _step(app, pilot)
        assert card.turn.thinking == "weighing the durable moat"
        assert "durable moat" in str(card._think_live.render())

        # The first TALK fragment auto-collapses the live block to the standard
        # ``▸ thinking`` row (content preserved, collapsed).
        q.put(_ev("talk_delta", turn_id="t1", text="I would buy Apple."))
        await _step(app, pilot)
        assert card.turn.thinking_live is False
        assert card._think_live.display is False
        assert card._think.display is True
        assert card._think.collapsed is True
        assert card.turn.speech == "I would buy Apple."
        assert "durable moat" in str(card._think_body.render())  # preserved

        # Re-expandable: the ``t`` key opens the collapsed row; the full thinking
        # is still there, now shown. A second press collapses it again.
        await pilot.press("t")
        await pilot.pause()
        assert card._think.collapsed is False
        assert "weighing the durable moat" in str(card._think_body.render())

        await pilot.press("t")
        await pilot.pause()
        assert card._think.collapsed is True


# --------------------------------------------------------------------------- #
# (b) The extended generator: deltas concatenate to the *_completed full_text.
# --------------------------------------------------------------------------- #

def test_b_delta_generator_fragments_concatenate_to_completed_full_text():
    events = read_events(G.to_jsonl(G.build_delta_events()).splitlines())

    think_frags: dict[str, list[str]] = defaultdict(list)
    talk_frags: dict[str, list[str]] = defaultdict(list)
    think_full: dict[str, str] = {}
    talk_full: dict[str, str] = {}
    order: dict[str, list[str]] = defaultdict(list)
    for e in events:
        t, p = e.type, e.payload
        if t in {"think_delta", "talk_delta", "think_completed", "talk_completed"}:
            order[p["turn_id"]].append(t)
        if t == "think_delta":
            think_frags[p["turn_id"]].append(p["text"])
        elif t == "talk_delta":
            talk_frags[p["turn_id"]].append(p["text"])
        elif t == "think_completed":
            think_full[p["turn_id"]] = p["full_text"]
        elif t == "talk_completed":
            talk_full[p["turn_id"]] = p["full_text"]

    assert len(think_full) == TOTAL_TURNS
    for tid in think_full:
        # Fragments join to exactly the completed text (delta/completed consistency).
        assert "".join(think_frags[tid]) == think_full[tid]
        assert "".join(talk_frags[tid]) == talk_full[tid]
        assert think_frags[tid], f"{tid} streamed no think_delta"
        assert talk_frags[tid], f"{tid} streamed no talk_delta"
        # Ordering: all think_delta before think_completed before all talk_delta
        # before talk_completed (turn-scoped, between turn_started and completion).
        seq = order[tid]
        ci, tci = seq.index("think_completed"), seq.index("talk_completed")
        assert ci < tci
        assert "think_delta" not in seq[ci:]
        assert "talk_delta" not in seq[tci:]


# --------------------------------------------------------------------------- #
# (b) A delta log folds to the identical final state as its completed-only twin.
# --------------------------------------------------------------------------- #

def _turn_view(t: TurnState):
    # Render-relevant fields only. ``thinking_streaming`` / ``talk_started`` are
    # deliberately excluded: those flip True on a delta log and are *meant* to
    # differ from the completed-only twin — the whole point of streaming. What
    # must match is the visible content and the final live/collapsed disposition.
    return (
        t.turn_id, t.persona, t.phase, t.role, t.target_persona,
        t.speech, t.thinking, t.stance, t.interrupted, t.completed, t.thinking_live,
    )


def _item_view(item):
    if isinstance(item, TurnState):
        return ("turn", _turn_view(item))
    if isinstance(item, PhaseState):
        return ("phase", item.phase, item.index, item.turn_count,
                item.completed, item.da_persona)
    if isinstance(item, SteeringState):
        return ("steer", item.msg_id, item.mode, item.text, item.status,
                item.target_persona, item.source, item.delivered_before_turn_id)
    if isinstance(item, ArtifactState):
        # Exclude the internal dedup ``key`` (some are keyed on applied_count,
        # which legitimately differs when extra delta events precede them).
        return ("artifact", item.kind, item.title, item.body)
    return ("?",)


def _persona_view(p):
    return (
        p.name, p.model_ref, p.auth_profile, p.thinking_level, p.temperament,
        p.mood, p.attention, p.goal, p.think, p.stance, p.vote, p.confidence,
        p.caved, p.speaking,
    )


def _snapshot(state: TownHallState) -> dict:
    return {
        "header": (
            state.ticker, state.company_name, state.preset,
            tuple(state.phases_completed), state.finished, state.errored,
            state.duration_s,
        ),
        "usage": (
            round(state.cost_usd, 8), state.input_tokens, state.output_tokens,
            state.cached_tokens, state.usage_calls, state.subscription_calls,
        ),
        "scorecard": dict(state.scorecard) if state.scorecard else None,
        "personas": [_persona_view(p) for p in state.personas.values()],
        "transcript": [_item_view(i) for i in state.transcript],
    }


def _fold(dicts) -> TownHallState:
    state = TownHallState()
    for event in read_events(G.to_jsonl(dicts).splitlines()):
        state.dispatch(event)
    return state


def test_b_delta_log_folds_to_identical_final_state_as_completed_twin():
    plain = _fold(G.build_events())
    delta = _fold(G.build_delta_events())

    # The render-relevant final state is identical (delta/completed consistency).
    assert _snapshot(delta) == _snapshot(plain)

    # ...and the equality is not vacuous: every turn of the delta twin actually
    # streamed live (the completed-only twin never did), yet all end collapsed.
    delta_streamed = sum(
        1 for i in delta.transcript
        if isinstance(i, TurnState) and i.thinking_streaming
    )
    plain_streamed = sum(
        1 for i in plain.transcript
        if isinstance(i, TurnState) and i.thinking_streaming
    )
    assert delta_streamed == TOTAL_TURNS
    assert plain_streamed == 0
    assert all(
        not i.thinking_live for i in delta.transcript if isinstance(i, TurnState)
    )


async def test_b_delta_log_replays_through_app_to_identical_final_render():
    delta_events = read_events(G.to_jsonl(G.build_delta_events()).splitlines())
    plain_events = read_events(G.to_jsonl(G.build_events()).splitlines())

    app = TownHallApp(events=delta_events, auto_replay=False, batch_size=1000)
    async with app.run_test() as pilot:
        app.replay_all_now()
        await pilot.pause()

        assert app.state.finished is True
        assert len(list(app.query(TurnCard))) == TOTAL_TURNS
        assert len(list(app.query(PersonaCard))) == 6
        header = str(app.query_one(StatusHeader).render()).lower()
        assert "complete" in header

        # No live block survives a fully-replayed delta log — every turn spoke.
        for card in app.query(TurnCard):
            assert card.turn.thinking_live is False
            assert card._think_live.display is False
            assert card._think.display is True

        # Final speech/thinking per turn match the completed-only twin exactly.
        plain_talk = {
            e.payload["turn_id"]: e.payload["full_text"]
            for e in plain_events if e.type == "talk_completed"
        }
        plain_think = {
            e.payload["turn_id"]: e.payload["full_text"]
            for e in plain_events if e.type == "think_completed"
        }
        for item in app.state.transcript:
            if isinstance(item, TurnState):
                assert item.speech == plain_talk[item.turn_id]
                assert item.thinking == plain_think[item.turn_id]


# --------------------------------------------------------------------------- #
# (c) turn_interrupted badge provenance + esc-through-ControlSink edge cases.
# --------------------------------------------------------------------------- #

async def test_c_system_interrupt_badge_shows_provenance_not_esc():
    q: queue.Queue = queue.Queue()
    app = TownHallApp.live(q, auto_replay=False)
    async with app.run_test() as pilot:
        await pilot.pause()
        for ev in (
            _ev("debate_started", ticker="T", personas=[{"name": "Solo"}]),
            _ev("phase_started", phase="opening", index=0),
            _ev("turn_started", turn_id="t1", persona="Solo",
                phase="opening", role="statement"),
            _ev("think_delta", turn_id="t1", text="mid thought"),
            # A provider/system interrupt — NOT the user's esc affordance.
            _ev("turn_interrupted", turn_id="t1", persona="Solo",
                by="system", disposition="discarded_on_arrival"),
        ):
            q.put(ev)
        app.replay_all_now()
        await pilot.pause()

        card = _card(app, "t1")
        assert card.turn.interrupted is True
        assert card.turn.interrupted_by == "system"
        assert card.turn.thinking_live is False       # interrupt clears the block
        assert card._think_live.display is False
        head = str(card._head.render())
        assert "interrupted" in head
        assert "(system)" in head
        assert "(esc)" not in head                     # not mislabelled as user esc
        assert "discarded_on_arrival" in head


async def test_c_esc_with_no_active_turn_records_request_with_null_turn():
    q: queue.Queue = queue.Queue()
    app = TownHallApp.live(q, auto_replay=False)
    async with app.run_test() as pilot:
        await pilot.pause()
        assert isinstance(app._control, RecordingControlSink)
        # Only lifecycle folded — no speaker is active.
        for ev in (
            _ev("debate_started", ticker="T", personas=[{"name": "Solo"}]),
            _ev("phase_started", phase="opening", index=0),
        ):
            q.put(ev)
        app.replay_all_now()
        await pilot.pause()
        assert app.state.current_turn_id is None

        await pilot.press("escape")
        await pilot.pause()

        # The request still goes through the sink (never a fabricated interrupt),
        # carrying a null turn_id since there was no current speaker.
        assert len(app._control.requests) == 1
        assert app._control.requests[0].turn_id is None
        assert app._control.requests[0].source == "tui"
        # No transcript turn was invented, nothing marked interrupted.
        assert _turn_count(app) == 0


# --------------------------------------------------------------------------- #
# (d) A JSONL follower feeds the UI live; mid-test appends appear; truncated
#     tail is tolerated, then cleanly reassembled.
# --------------------------------------------------------------------------- #

async def test_d_follower_feeds_ui_incrementally_and_tolerates_truncated_tail(tmp_path):
    path = tmp_path / "run.jsonl"
    # Pre-existing prefix at attach time: a debate + one full streamed turn (t1),
    # no terminal event yet (the debate is still running in another process).
    path.write_text(
        _line(_env(1, "debate_started", ticker="AAPL",
                   personas=[{"name": "Warren Buffett"}]))
        + _line(_env(2, "phase_started", phase="opening", index=0))
        + _line(_env(3, "turn_started", turn_id="t1", persona="Warren Buffett",
                     phase="opening", role="statement"))
        + _line(_env(4, "think_delta", turn_id="t1", text="weighing the moat"))
        + _line(_env(5, "talk_delta", turn_id="t1", text="I would buy."))
        + _line(_env(6, "talk_completed", turn_id="t1", full_text="I would buy."))
        + _line(_env(7, "turn_completed", turn_id="t1", persona="Warren Buffett",
                     phase="opening", interrupted=False)),
        encoding="utf-8",
    )

    q: queue.Queue = queue.Queue()
    follower = attach_event_log_follower(path, q, poll_interval=0.01)
    app = TownHallApp.live(q, auto_replay=False)
    try:
        async with app.run_test() as pilot:
            await pilot.pause()

            # The pre-existing prefix streams into the UI, whole turn and all.
            assert await _drain_until(
                app, pilot, lambda: _turn_speech(app, "t1") == "I would buy."
            )
            assert app.state.ticker == "AAPL"
            assert _card(app, "t1").turn.speech == "I would buy."
            assert app.state.finished is False        # no terminal yet

            # Mid-test: append a SECOND turn (t2) plus a truncated final record —
            # bytes with no closing newline, exactly what a crash mid-write leaves.
            _append(path, _line(_env(8, "turn_started", turn_id="t2",
                                     persona="Warren Buffett", phase="opening",
                                     role="statement")))
            _append(path, _line(_env(9, "think_delta", turn_id="t2",
                                     text="second thought")))
            _append(path, _line(_env(10, "talk_completed", turn_id="t2",
                                     full_text="I hold.")))
            _append(path, _line(_env(11, "turn_completed", turn_id="t2",
                                     persona="Warren Buffett", phase="opening",
                                     interrupted=False)))
            _append(path, '{"v":1,"seq":12,"type":"talk_de')  # half-written line

            # t2 lands in full; the partial line is held in the follower's buffer,
            # so it neither crashes the UI nor fabricates a third turn.
            assert await _drain_until(
                app, pilot, lambda: _turn_speech(app, "t2") == "I hold."
            )
            assert _card(app, "t2").turn.speech == "I hold."
            assert _turn_count(app) == 2
            assert app.state.finished is False

            # Complete the partial record (reassembled into a valid, no-op delta),
            # then a terminal event: the debate finishes cleanly, no turn lost or
            # invented, the truncated bytes never corrupting the stream.
            _append(path, 'lta","payload":{"turn_id":"t2","text":""}}\n')
            _append(path, _line(_env(13, "debate_completed",
                                     phases_completed=["opening"],
                                     duration_s=1.0, result_ref="x")))

            assert await _drain_until(app, pilot, lambda: app.state.finished)
            assert _turn_count(app) == 2
            assert _card(app, "t2").turn.speech == "I hold."
            header = str(app.query_one(StatusHeader).render()).lower()
            assert "complete" in header
    finally:
        follower.stop()
        follower.join(timeout=5.0)
