"""Cited, offline-testable investor-persona research factory."""

from .pipeline import (
    BackendContractError,
    BuiltinPersonaCollisionError,
    DISCLAIMER,
    EvidenceLedger,
    InsufficientSourcesError,
    InvalidSlugError,
    LOW_SOURCE_WARNING,
    PROTECTED_BUILTIN_SLUGS,
    PersonaCollisionError,
    PersonaFactory,
    PersonaFactoryError,
    canonicalize_url,
    quality_for,
    resolve_personas_dir,
    slugify,
    write_artifact_pair,
)
from .schema import AGENT_SCHEMA, SchemaValidationError, validate_agent_spec
from .seeds import CANONICAL_SEEDS, EDGAR_13F_SEED, canonical_seeds, plan_queries
from .types import (
    AtomicClaim,
    CallUsage,
    DossierSynthesisRequest,
    DossierSynthesisResponse,
    Evidence,
    PersonaSynthesisRequest,
    PersonaSynthesisResponse,
    QueryPlan,
    ResearchBackend,
    ResearchRequest,
    ResearchResult,
    SearchQuery,
    SearchRequest,
    SearchResponse,
    SeedSource,
    UsageSummary,
    VerificationRequest,
    VerificationResponse,
)

__all__ = [
    "AGENT_SCHEMA",
    "AtomicClaim",
    "BackendContractError",
    "BuiltinPersonaCollisionError",
    "CANONICAL_SEEDS",
    "CallUsage",
    "DISCLAIMER",
    "DossierSynthesisRequest",
    "DossierSynthesisResponse",
    "EDGAR_13F_SEED",
    "Evidence",
    "EvidenceLedger",
    "InsufficientSourcesError",
    "InvalidSlugError",
    "LOW_SOURCE_WARNING",
    "PROTECTED_BUILTIN_SLUGS",
    "PersonaCollisionError",
    "PersonaFactory",
    "PersonaFactoryError",
    "PersonaSynthesisRequest",
    "PersonaSynthesisResponse",
    "QueryPlan",
    "ResearchBackend",
    "ResearchRequest",
    "ResearchResult",
    "SchemaValidationError",
    "SearchQuery",
    "SearchRequest",
    "SearchResponse",
    "SeedSource",
    "UsageSummary",
    "VerificationRequest",
    "VerificationResponse",
    "canonical_seeds",
    "canonicalize_url",
    "plan_queries",
    "quality_for",
    "resolve_personas_dir",
    "slugify",
    "validate_agent_spec",
    "write_artifact_pair",
]
